spring:
  banner:
    image:
      location:
        classspath: banner.txt
  h2:
    console:
      enable: true
      path: /h2
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:appdb
    username: sa
    password: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect