spring:
  banner:
    image:
      location:
        classspath: banner.txt
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: user-root
    password: senha-mysql
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
